version: '3'
services:
  db:
    image: mysql:8.0
    container_name: db
    environment:
      MYSQL_ROOT_PASSWORD: password
    ports:
      - '3306:3306'
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - mysql-data:/var/lib/mysql
      
  animal-system: &copy-animal-system
    build: ./animal-system
    container_name: animal-system
    command: rails s -p 3000 -b '0.0.0.0'
    volumes:
      - ./animal-system:/animal-system
    ports:
      - "3000:3000"
    depends_on:
      - db
    stdin_open: true
    tty: true

  webpack:
    <<: *copy-animal-system
    command: "bin/webpack-dev-server"
    container_name: webpack
    ports:
      - "3035:3035"
    depends_on:
      - animal-system
    tty: false
    stdin_open: false

volumes:
  mysql-data:
    driver: local
